server:
  port: 8088

spring:
  application:
    name: luffy
  profiles:
    active:
      - secure


# Eureka相应的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.71.119:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false #使用feign时需要指定为false，否则注册到ribbon服务列表上的服务显示机器名
    instance-id: ${spring.cloud.client.ip-address}-${server.port} #在eureka注册表上显示ip:port
    health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: ALWAYS  #health endpoint是否必须显示全部细节

---
spring:
  profiles: insecure

---
# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: admin123

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}         #These two are needed so that the server
      user.password: ${spring.security.user.password} #can access the protected client endpoints
